konflux-ci/konflux-ui

Dockerfile

chore: add dockerfile

---

.github/workflows/main.yaml
.github/workflows/main.yml
codecv.yml
src/components/PipelineRun/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx

fixes: https://issues.redhat.com/browse/KFLUXUI-209

chore(github-actions): add github-actions for unit tests and lint

---

.github/workflows/post-merge.yaml

Add coverage for main branch to enable codecov to count a diff between new branches and main.

Fix Codecov reports

---

codecv.yml
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
src/components/Commits/CommitDetails/visualization/__tests__/CommitVisualization.spec.tsx
src/components/Commits/CommitDetails/visualization/useCommitWorkflowData.ts
src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/components/SnapshotDetails/SnapshotDetailsView.tsx
src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx
src/hooks/__tests__/useApplicationReleases.spec.ts
src/hooks/useApplicationReleases.ts
src/hooks/useReleasePlans.ts

https://issues.redhat.com/browse/KFLUXUI-218

fix(Release): remove managed envs from commmit details and release, fix release details view

---

src/utils/pipeline-utils.ts

Migration of KFLUXBUGS-1485 to the new repo.
Assure during the migration we move our latest changes.

fix(KFLUXBUGS-1485): cancelled state on stopped runs

---

src/components/IntegrationTests/FormikParamsField.tsx

backport of [KFLUXBUGS-1648](https://issues.redhat.com/browse/KFLUXBUGS-1648)

fix(KFLUXUI-184): display parameter name for IntegrationTests

---

src/components/PipelineRun/PipelineRunListView/PipelineRunsListView.tsx
src/shared/components/table/Table.tsx

adds loading indicator for pipeline run list view

fix: loading indicator for the pipeline runs list view

---

.codecov.yml

fix: update codecov color range, target codecov of 80% for patch

---

.github/workflows/pr-check.yaml

Fixing E2E tests in PR check.
Part of https://issues.redhat.com/browse/KFLUXUI-338

test(fix): fix check for author to be part of an org

---

src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
src/components/Commits/CommitDetails/sidepanels/IntegrationTestSidePanel.tsx
src/components/Commits/CommitDetails/visualization/useCommitWorkflowData.ts
src/components/IntegrationTests/IntegrationTestDetails/IntegrationTestDetailsView.tsx
src/components/IntegrationTests/IntegrationTestDetails/tabs/IntegrationTestOverviewTab.tsx
src/components/IntegrationTests/IntegrationTestDetails/tabs/IntegrationTestPipelineRunTab.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestEditForm.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestView.tsx
src/components/IntegrationTests/IntegrationTestsListView/IntegrationTestListRow.tsx
src/components/IntegrationTests/IntegrationTestsListView/IntegrationTestsListView.tsx
src/components/IntegrationTests/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
src/hooks/__tests__/useLatestIntegrationTestPipelines.spec.ts
src/hooks/useIntegrationTestScenarios.ts
src/hooks/useLatestIntegrationTestPipelines.ts
src/routes/index.tsx
src/routes/page-routes/integration-test.tsx
src/routes/paths.ts

[WIP] yet to test properly
https://issues.redhat.com/browse/KFLUXUI-297

feat(integrationtests): remove workspace from integration tests

---

src/components/Commits/CommitDetails/tabs/__tests__/CommitsPipelineRunTab.spec.tsx
src/components/PipelineRun/PipelineRunDetailsView/__tests__/PipelineRunEmptyState.spec.tsx
src/components/PipelineRun/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRun/PipelineRunEmptyState.tsx
src/components/PipelineRun/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/SnapshotDetails/SnapshotDetailsView.tsx
src/components/SnapshotDetails/index.ts
src/components/SnapshotDetails/tabs/SnapshotComponentsEmptyState.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsListRow.tsx
src/components/SnapshotDetails/tabs/SnapshotOverview.tsx
src/components/SnapshotDetails/tabs/SnapshotPipelineRunsTab.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsEmptyState.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsList.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsTab.spec.tsx
src/components/SnapshotDetails/utils/snapshot-utils.ts
src/routes/index.tsx
src/routes/page-routes/snapshots.tsx
src/routes/paths.ts
tsconfig.json

https://issues.redhat.com/browse/KFLUXUI-336
Review Snapshot details page with Overview tab and pipeline runs tab.
Trigger a release => Go to release details view => click on snapshot link => Go to snapshot details view

fix: migrate workspace for Snapshot details view

---

src/components/Commits/CommitsListPage/__tests__/CommitsListView.spec.tsx
src/components/Commits/__data__/pipeline-with-commits.ts
src/utils/__tests__/commits-utils.spec.ts
src/utils/commits-utils.ts

[KONFLUX-5942](https://issues.redhat.com/browse/KONFLUX-5942)
Change the if statement to use the older time, which is when the changed were pushed, instead of the more recent, which is last time pipeline run.
1. Create a PR for a test component in Konflux
2. Check the commits tab for this component
3. Get the time in the `Last commit at` column
4. In the PR, comment `/retest` to trigger the pipeline again
5. Check the commits tab for this component. The pipeline associated to this commit should run again and the time in `Last commit at` should be the same of step 3.
6. Push a new commit in the PR
7. Should be a new commit in commits tab for this component
8. Get the time in the `Last commit at` column
9. In the PR, comment `/retest` to trigger the pipeline again
10. Check the commits tab …

fix(KONFLUX-5942): set the correct commit time instead of last pipelinerun

---

src/components/Commits/CommitsListPage/__tests__/CommitsListView.spec.tsx

fix: fixing typo in tests

---

src/components/ReleaseService/ReleasePlan/ReleasePlanListView.tsx

https://issues.redhat.com/browse/KONFLUX-7221
add loaded check to prevent undefined release plan failure
Before fix:
Go to release plan list page and reload the page couple of time to trigger error `Can not read property of undefined`

fix: add loaded check for release plan filters

---

.github/workflows/main.yaml
package.json
src/components/Commits/CommitsListPage/__tests__/CommitsListView.spec.tsx

https://issues.redhat.com/browse/KFLUXUI-390
This PR adds typescript type checking to github actions
no UI changes
monitor github actions and make sure type check step runs successfully

chore: add type checking in github actions

---

src/auth/AuthContext.tsx
src/auth/type.ts
src/auth/useAuth.ts
src/auth/utils.ts
src/utils/__tests__/rbac.spec.ts
src/utils/rbac.ts

https://issues.redhat.com/browse/KFLUXUI-384
add username and system:authenticated group to the subject access review checks. This will resolve issue with viewing release pipeline in managed namespace.
Subject access review checks should work
No UI changes
Subject access review checks should work as expected.

fix: add system:authenticated group to subject access review checks

---

src/__data__/rolebinding-data.ts
src/components/NamespaceList/NamespaceListView.tsx
src/components/UserAccess/UserAccessForm/form-utils.ts
src/types/role-binding.ts

https://issues.redhat.com/browse/KFLUXUI-391
Update User Access and link to documentation
1. Go to create namespace instructions button leads to the old doc (https://konflux.pages.redhat.com/docs/users/getting-started/getting-access.html), it should point to https://konflux.pages.redhat.com/docs/users/getting-started/getting-access-new.html 
2. Remove `namespace` from RoleBinding `subject`

fix(rolebinding): update doc link and rb subject field

---

.tekton/konflux-ui-pull-request.yaml
.tekton/konflux-ui-push.yaml

chore: add sast-unicode-check task

---

.github/workflows/pr-check.yaml

test(fix): fix konflux deployment by consuming changes from [PR#1852](https://github.com/konflux-ci/konflux-ci/pull/1852)

unblock e2e tests

---

e2e-tests/tests/basic-happy-path.spec.ts
e2e-tests/utils/Applications.ts

https://issues.redhat.com/browse/KFLUXUI-338
Stablise tests:
- Sending/Merge pull request label of a button under the Build pipeline plan is ignored, test just click the button
- Test checks for the on-pull-request pipeline to be either Cancelled or Cancelling

test: stabilize e2e test flow

---

e2e-tests/support/pages/ComponentsPage.ts

https://issues.redhat.com/browse/KFLUXUI-338
Test can't click on a button which is hidden above the text bubble. Stabilise the test.

fix(test): fix test flakiness

---

.github/actions/konflux-ui-deploy-test/action.yaml
.github/workflows/periodic-job.yaml
.github/workflows/pr-check.yaml
Dockerfile.sealights
pr_check.sh

https://issues.redhat.com/browse/KFLUXDP-220
https://issues.redhat.com/browse/KFLUXDP-179
* added reusable composite action used by PR and periodic workflow: `.github/actions/konflux-ui-deploy-test/action.yaml`
* updates to the github workflow for e2e testing (now testing directly against an image deployed via konflux-ci scripts instead of `yarn start`)
* updates to the testing scripts
* added Dockerfile.sealights
* changes to the workflow and scripts were tested in [this PR](https://github.com/psturc/konflux-ui/pull/6/commits)
cc @Katka92

test: onboard Sealights for PR and periodic testing

---

.tekton/konflux-ui-pull-request.yaml

https://issues.redhat.com/browse/KFLUXUI-359

chore: [KFLUXUI-359] update konflux references to enable build in merge queue

---

docs/feature-flags.md
src/components/Header/Header.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/feature-flags/Panel.tsx
src/feature-flags/__tests__/store.spec.tsx
src/feature-flags/flags.ts
src/feature-flags/hooks.tsx
src/feature-flags/store.ts

https://issues.redhat.com/browse/KFLUXUI-451
Please go through the added readme for feature flags

feat(FeatureFlags): [KFLUXUI-451] add feature flags capability

---

src/components/Secrets/SecretsForm/AddSecretForm.tsx
src/components/Secrets/secret-actions.ts
src/components/Secrets/secret-modal.tsx
src/components/Secrets/utils/__tests__/service-account-utils.spec.ts
src/components/Secrets/utils/service-account-utils.ts
src/consts/pipeline.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

[KFLUXUI-460](https://issues.redhat.com/browse/KFLUXUI-460)
Enjoy the feature flag to PR of  KFLUXUI-416.
The the feature flag is enable, new feature component would be shown and functions would call the new feature methods.
Unless, it would keep as same as before.
https://github.com/user-attachments/assets/9a7b3cd7-64c5-499e-99c6-32815d7f5508
- without enable the feature flag, try the create secret and delete secret, to ensure it works well as before.
- with enable the feature, we could create secret with linking components well.

 feat(KFLUXUI-460): add the feature flag for KFLUXUI-416

---

src/components/Secrets/utils/service-account-utils.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/KONFLUX-6596
image pull secret doesn't get associated with the appstudio-pipeline SA when the secret is created via the Component creation flow
Adds linktoserviceAccount step for image pull secrets in build time

fix(secret): link image pull to service account

---

src/components/UserAccess/RBListHeader.tsx
src/components/UserAccess/RBListRow.tsx
src/components/UserAccess/__tests__/RBListRow.spec.tsx

[KFLUXUI-414](https://issues.redhat.com/browse/KFLUXUI-414)
Add column to user access list view page to inform the Role Binding associated with roles. Since the ticket does not ask to edit/delete RBs this PR only takes care of display them.
1. Access konflux
2. Go to `User Access tab
3. You should see Role Binding column with the role binding associated with a role.

feat(KFLUXUI-414): add rb to user access list page

---

src/components/PipelineRun/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
src/components/PipelineRun/PipelineRunListView/__tests__/ScanStatus.spec.tsx
src/components/PipelineRun/ScanDetailStatus.tsx
src/hooks/__tests__/useScanResults.spec.ts
src/hooks/useScanResults.ts

Fixes: https://issues.redhat.com/browse/KFLUXUI-33
Unknown vulnerability type wasn't being shown.
Note that  <code>SeverityUndefinedIcon</code> was meant to be used as an icon, however it's not available in the current version of @paternfly/react-icons lib (5.3.2). For now <code>UnknownIcon</code> is used instead. 
Before:
After:
View website -> go to Namespaces -> go to your namespace -> select one of your applications -> go to Activity tab and see whether it shows unknown vulnerabilities.

fix(KFLUXUI-33): show unknown vulnerability

---

.husky/commit-msg
AI_authorized_emails.txt

feat(KONFLUX-8516): adding AI tagging

---

AI_authorized_emails.txt

Updated AI_authorized_emails.txt

---

src/components/Secrets/SecretsListView/SecretsListRow.scss

https://issues.redhat.com/browse/KFLUXUI-530
UX change for help-popover content of import secret

feat: ux improvement for import secret

---

src/components/ImportForm/ComponentSection/SourceSection.tsx
src/components/ImportForm/validation.utils.ts
src/utils/validation-utils.ts

<a href="https://issues.redhat.com/browse/KONFLUX-7849">KONFLUX-7849</a>
This fix helps to show what exactly is missing/required in git repository url.

fix(KONFLUX-7849): git repository errors

---

src/components/DetailsPage/DetailsPage.tsx
src/components/PipelineRun/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/components/PipelineRun/PipelineRunListView/PipelineRunListHeader.tsx
src/components/PipelineRun/PipelineRunListView/PipelineRunListRow.tsx
src/components/PipelineRun/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx
src/components/Releases/ReleaseDetailsView.tsx
src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/ReleasePipelineRunTab.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/__tests__/ReleasePipelineRunTab.spec.tsx
src/components/Releases/index.ts
src/consts/pipelinerun.ts
src/routes/page-routes/release.tsx
src/routes/paths.ts

https://issues.redhat.com/browse/KFLUXUI-518
Create pipeline run tab in the release plan and handle the navigation for the snapshot

feat(KFLUXUI-518-): create pipeline run tab in the release plan

---

src/utils/validation-utils.ts

<a href="https://issues.redhat.com/browse/KFLUXUI-556">KFLUXUI-556</a>
Git Repo URL while creating a component was not accepting Gitlab URLs, which is fixed with change in regex.
GitLab URL
<br><br>
GitHub URL
1. Go to Applications
2. Create a new component
3. Add Github/Gitlab urls in Git Repository URL field

fix(KFLUXUI-556): regex fixed to accept all git urls

---

src/components/Filter/utils/pipelineruns-filter-utils.ts
src/components/PipelineRun/PipelineRunListView/PipelineRunsListView.tsx
src/utils/__tests__/tekton-results.spec.ts
src/utils/tekton-results.ts

Fixes https://issues.redhat.com/browse/KFLUXUI-557
This PR fixes an issue related with the expression that we were using to filter tekton-results by name.
Before:
https://github.com/user-attachments/assets/0630ae2c-664a-4da2-a223-b4ba3608ee67
After:
https://github.com/user-attachments/assets/a5a071d6-fe06-4994-b3ad-60f781dfc3b0
* go to Activity -> "Pipeline runs" tab
* try filtering by a PLR name
* notice that it will return PLRs which names contains the text that you searched, not only the ones in which the name starts with the searched text
* :coffee:

KFLUXUI-557 [PipelineRuns List View] Fix filtering by name

---

docs/kubearchive.md
src/kubearchive/hooks.ts
src/kubearchive/resource-utils.ts

Assisted-by: Cursor
https://issues.redhat.com/browse/KFLUXUI-539
add tech docs for kubearchive utils

fix: add docs for kubearchive implementation

---

src/components/PipelineRun/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/hooks/useUIInstance.ts
src/types/konflux-public-info.ts
src/utils/pipeline-utils.ts

https://issues.redhat.com/browse/KFLUXUI-463
Should go in after -> https://github.com/redhat-appstudio/infra-deployments/pull/6418

feat(pipelineruns): update sbom template

---

src/components/WhatsNext/WhatsNextSection.tsx
src/components/WhatsNext/useWhatsNextItems.ts

https://issues.redhat.com/browse/KFLUXUI-269
Adds a What'sNextCard for GitLab

feat(components): add a card for gitlab imports

---

src/components/ImportForm/submit-utils.ts

Assisted-by: Cursor
Create application before creating the Integration test scenario

fix: create application before ITS dry run request

---

@types/index.d.ts
package.json
src/components/Overview/InfoBanner.tsx
src/components/Overview/IntroBanner.scss
src/components/Overview/IntroBanner.tsx
src/components/Secrets/SecretsListPage.tsx
src/components/UserAccess/UserAccessListPage.tsx
src/components/UserAccess/UserAccessListView.tsx
src/main.scss
src/shared/components/pipeline-run-logs/PipelineRunLogs.scss
src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.scss
webpack.config.js
yarn.lock

Assisted-by: Cursor
https://issues.redhat.com/browse/KFLUXUI-606
- Fixes visual inconsistencies on the UserAccess and Secrets page
- Fixes color on the logs component
- Adds a webpack to use SVGs as React components, so they can adapt to the theme change
- Fixes Overview page SVG and colors
- Adds primary and primary hover color for the dark theme

fix: visual inconsistencies in the dark theme
