konflux-ci/konflux-ui

src/k8s/k8s-utils.ts

When connecting to the k8s api using a websocket
the "base64.binary.k8s.io" subprotocol should be mentioned.

fix: websocket connection to the k8s api

---

src/components/ImportForm/ComponentSection/GitOptions.tsx

Using a tag or commit can have unintended consequences. Lets only recommend that users use a branch when setting up their components.
Backport of https://github.com/openshift/hac-dev/pull/1004

fix(KFLUXUI-185): only suggest branches

---

src/components/Applications/ApplicationListView.tsx
src/components/Applications/__tests__/ApplicationListView.spec.tsx

feat(KFLUXUI-193): filter on Applications

---

src/components/Secrets/SecretForm.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/components/Secrets/__tests___/AddSecretForm.spec.tsx
src/components/Secrets/__tests___/SecretTypeSubForm.spec.tsx

Migration of KFLUXBUGS-96 to the new repo.
Assure during the migration we move our latest changes.

fix(KFLUXBUGS-96): make the secret forms more clear 

---

src/components/Components/ComponentsListView/ComponentListView.tsx
src/components/EnterpriseContract/useEnterpriseContractResultFromLogs.tsx
src/components/PipelineRun/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/hooks/__tests__/useTektonResults.spec.tsx
src/hooks/useApplicationReleases.ts
src/hooks/useComponents.ts
src/hooks/useReleases.ts
src/hooks/useTektonResults.ts
src/k8s/hooks/__tests__/useK8sQueryWatch.spec.ts
src/k8s/hooks/useK8sQueryWatch.ts
src/k8s/hooks/useK8sWatchResource.ts
src/k8s/k8s-utils.ts
src/shared/components/pipeline-run-logs/logs/TektonTaskRunLog.tsx
src/shared/components/pipeline-run-logs/logs/logs-utils.ts
src/utils/__tests__/tekton-results.spec.ts
src/utils/common-utils.tsx
src/utils/tekton-results.ts

https://issues.redhat.com/browse/KFLUXUI-229

fix(pipeline-run): open websocket in case of abnormally closed, implement polling, releases watch

---

src/components/IntegrationTests/ContextSelectList.tsx
src/components/IntegrationTests/ContextsField.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestSection.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestView.tsx
src/components/IntegrationTests/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/types.ts
src/components/IntegrationTests/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTests/IntegrationTestForm/utils/create-utils.ts
src/components/IntegrationTests/__tests__/ContextSelectList.spec.tsx
src/components/IntegrationTests/__tests__/ContextsField.spec.tsx
src/components/IntegrationTests/utils.tsx

Allows users to set context values, both in the edit and create integration page.
By default the 'application' context should be selected when creating a new integration test.
Backport of https://github.com/openshift/hac-dev/pull/997

feat(KFLUXUI-191): allow users to set context

---

src/components/PipelineRun/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx
src/components/PipelineRun/PipelineRunListView/pipelinerun-actions.tsx

JIRA: KFLUXBUGS-1910
Port of https://github.com/openshift/hac-dev/pull/1029

fix(KFLUXBUGS-1910): add Gitlab push event type

---

src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/types/release.ts

fix(KFLUXUI-190): use status.managedProcessing to get the pipelineRun for Release

---

src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx
src/components/GitLink/GitRepoLink.tsx
src/shared/components/links/ExternalLink.scss
src/shared/components/links/ExternalLink.tsx

fix(KFLUXUI-246): allow highlightable links

---

src/components/ComponentRelation/ComponentRelationForm.tsx
src/components/ComponentRelation/ComponentRelationModal.tsx
src/components/ComponentRelation/__tests__/ComponentRelationForm.spec.tsx
src/components/ComponentRelation/__tests__/ComponentRelationModal.spec.tsx
src/components/ComponentRelation/__tests__/ComponentRelationshipDropdowns.spec.tsx
src/components/ComponentRelation/__tests__/useComponentRelationAction.spec.ts
src/components/ComponentRelation/__tests__/utils.spec.ts
src/components/ComponentRelation/cr-modals.tsx
src/components/ComponentRelation/utils.ts

fix(KFLUXUI-198): component relationship remove button

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/Components/ComponentDetails/ComponentDetailsView.tsx
src/components/Components/ComponentsListView/ComponentListView.tsx
src/components/Components/component-actions.tsx
src/components/WhatsNext/useWhatsNextItems.ts

Fixes https://issues.redhat.com/browse/KFLUXUI-188
Backport of https://github.com/openshift/hac-dev/pull/1001

fix(KFLUXUI-188): disable pipeline actions for contributors

---

src/components/IntegrationTests/ContextsField.tsx
src/components/IntegrationTests/EditContextsModal.tsx
src/components/IntegrationTests/IntegrationTestDetails/tabs/IntegrationTestOverviewTab.tsx
src/components/IntegrationTests/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTests/IntegrationTestForm/utils/create-utils.ts
src/components/IntegrationTests/__tests__/EditContextsModal.spec.tsx

- Add the context values to the integration show page.
- Add a modal to allow easy edits.
- Use spinner for loading instead of text.
backport of https://github.com/openshift/hac-dev/pull/1008

feat(KFLUXUI-217): add contexts to show page

---

src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/components/Releases/__tests__/ReleasesListRow.spec.tsx
src/hooks/__tests__/useReleaseStatus.spec.ts
src/hooks/useReleaseStatus.ts

https://issues.redhat.com/browse/KFLUXUI-245

fix(KFLUXBUGS-1751): release status replies on status and reason of the release type

---

src/components/EnterpriseContract/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContract/useEnterpriseContractResultFromLogs.tsx

Backport fix(pipeline): null check on status of taskrun to the new repo.
Assure during the migration we move our latest changes.

fix(pipeline): null check on status of taskrun

---

src/components/Components/ComponentsListView/ComponentListView.tsx
src/components/Components/ComponentsListView/ComponentsListRow.tsx

https://issues.redhat.com/browse/KONFLUX-5766
The components list page takes too long to load because it waits for all pipeline runs to be fetched. Since an application can have a large number of associated pipeline runs, the UI currently fetches only 30 pipeline runs per request, causing the page to wait until all requests are completed.
Proposed Solution:
The UI should load the page as soon as the components are available and fetch the pipeline runs in the background. Each row should display a loading indicator for the pipeline runs. As soon as the pipeline run for a specific component is fetched, it should be displayed on the UI while the remaining pipeline runs continue to load in the background.
**NOTE**:
Added a script to create large number of components for testing purposes. I …

fix: unblock component list loading from pipeline runs

---

src/components/Workspace/__tests__/workspace-context.spec.tsx
src/components/Workspace/workspace-context.tsx
src/routes/index.tsx

https://issues.redhat.com/browse/KFLUXUI-225

fix: workspace provider to use the correct last used workspace

---

src/components/ReleaseService/ReleasePlan/ReleasePlanForm/ReleasePlanForm.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/RunReleasePipelineSection.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/ReleasePlanForm.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/RunReleasePipelineSection.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/form-utils.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanListHeader.tsx

https://issues.redhat.com/browse/KONFLUX-5721
1. We change the workspace to namespace in konflux release section.
2. When users create/edit the release plan, konflux ui do not append the suffix '-tenant' to the input target namespace automatically.
- [] Refactoring (no functional changes, no api changes)
- [] Documentation content changes
1. releases page
2. create release page
3. edit release plan
1. Navigate to 'Releases'. 
2. Create one RPA 
3. Create one release
4. edit the release
Excepted Results: 
All pages show 'target namespace' and when we change the target namespace, there is no '-tenant' appended by UI.

fix(KONFLUX-5721): change workspace to namespace for release and do not  append suffix to namespace

---

e2e-tests/support/pages/tabs/IntegrationTestsTabPage.ts
src/components/IntegrationTests/IntegrationTestDetails/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestSection.tsx
src/components/IntegrationTests/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTests/IntegrationTestForm/utils/create-utils.ts
src/components/IntegrationTests/IntegrationTestsListView/IntegrationTestListHeader.ts
src/components/IntegrationTests/IntegrationTestsListView/IntegrationTestsListView.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/RunReleasePipelineSection.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/RunReleasePipelineSection.spec.tsx

https://issues.redhat.com/browse/KFLUXUI-266
Add/Edit Release Plan Page:
Add/Edit Integration Test Page:
Integration Tests List:
Replace GitHub mentions with Git in:
1. Add and edit release plan pages.
2. Add and edit integration test pages.
3. Page that lists releases(NA)

feat(KFLUXUI-266): Replaced GitHub mentions with Git 

---

e2e-tests/support/pages/tabs/IntegrationTestsTabPage.ts
src/components/IntegrationTests/IntegrationTestDetails/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/IntegrationTestSection.tsx
src/components/IntegrationTests/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/components/IntegrationTests/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTests/IntegrationTestForm/utils/create-utils.ts
src/components/IntegrationTests/IntegrationTestsListView/IntegrationTestListHeader.ts
src/utils/__tests__/commits-utils.spec.ts
src/utils/__tests__/component-utils.spec.ts

[Replace GitHub mentions with Git - part2](https://issues.redhat.com/browse/KFLUXUI-267)

feat(KFLUXUI-267): replace GitHub with Git

---

src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts
src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx
src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx
src/components/Components/ComponentDetails/tabs/__tests__/ComponentDetailsTab.spec.tsx
src/components/Components/ComponentsListView/ComponentsListRow.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx
src/types/component.ts
src/utils/__tests__/component-utils.spec.ts
src/utils/component-utils.ts

The integration service recently migrated from using the component's spec.containerImage field to store the latest image to using the component's status.lastPromotedImage field. 
The patch support the component.spec.containerImage as the latestImage when it's valid.

chore(KFLUXUI-256): support component.spec.containerImage as latestImage

---

src/components/ImportForm/SecretSection/SecretSection.tsx
src/components/ImportForm/SecretSection/__tests__/SecretSection.spec.tsx
src/components/ImportForm/__tests__/submit-utils.spec.ts
src/components/ImportForm/submit-utils.ts
src/components/ImportForm/type.ts
src/components/Secrets/SecretForm.tsx
src/components/Secrets/SecretModal.tsx
src/components/Secrets/SecretModalLauncher.tsx
src/components/Secrets/__tests___/SecretModal.spec.tsx
src/components/Secrets/__tests___/secret-utils.spec.ts
src/components/Secrets/utils/secret-utils.ts
src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.tsx
src/types/secret.ts
src/utils/validation-utils.ts

[KFLUXBUGS-1342](https://issues.redhat.com//browse/KFLUXBUGS-1342)
When onboarding a new component and adding a build time secret, the dialog cannot find an existing secret in the workspace.

fix(KFLUXBUGS-1342): add existing secret in the components secret form

---

src/components/modal/resource-modals.tsx

Fixes - [KFLUXUI-258](https://issues.redhat.com/browse/KFLUXUI-258) & [KONFLUX-6195](https://issues.redhat.com/browse/KONFLUX-6195)
Updates content for ApplicationDeleteModal & ComponentDeleteModal

fix(deletemodal): update microcopy based content

---

src/utils/create-utils.ts

https://issues.redhat.com/browse/KFLUXUI-223
**UI: shortened the prefix of ImageRepository names**

feat(KFLUXUI-223): shorten the prefix of ImageRepository names

---

src/components/ImportForm/SecretSection/SecretSection.tsx
src/components/PageAccess/NoAccessState.tsx
src/components/PageAccess/__tests__/NoAccessState.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/TriggerReleaseForm.tsx
src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListHeader.tsx
src/components/ReleaseService/ReleaseService.tsx
src/components/Secrets/SecretsListPage.tsx
src/components/UserAccess/UserAccessForm/EditAccessPage.tsx
src/components/UserAccess/UserAccessForm/UserAccessForm.tsx
src/components/UserAccess/UserAccessForm/UsernameSection.tsx
src/components/UserAccess/UserAccessForm/__tests__/UserAccessForm.spec.tsx
src/components/UserAccess/UserAccessForm/__tests__/UserAccessFormPage.spec.tsx
src/components/UserAccess/UserAccessListPage.tsx
src/components/UserAccess/UserAccessListView.tsx
src/utils/breadcrumb-utils.tsx
src/utils/pipeline-utils.ts

[KFLUXUI-279](https://issues.redhat.com/browse/KFLUXUI-279)
Replace all occurrences of `Workspace` in UI by `Namespace`
Current
After change

chore(KFLUXUI-279): replace Workspace by Namespace only in the UI

---

src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/CVEFormContent.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/CVEFormContent.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/TriggerRelease/form-utils.ts

[KONFLUX-6512](https://issues.redhat.com/browse/KONFLUX-6512)
Allow to add CVEs while releasing components

fix(KONFLUX-6512): restore allow input CVE for release

---

src/components/SnapshotDetails/tabs/SnapshotComponentsListRow.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx

https://issues.redhat.com/browse/KFLUXUI-268
The Revision reference on a Snapshot detail page is clickable and take the user to that particular commit detail page.
Snapshot Detail Page:
Commit Details Page:

chore(KFLUXUI-268): revision data on snapshot page is now clickable& directs to commit detail page

---

src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueModal.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueSection.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/BugFormContent.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/AddIssueSection.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/BugFormContent.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/TriggerRelease/form-utils.ts

https://issues.redhat.com/browse/KFLUXUI-122
Updates Response payload and form for attaching Bugs to releases

feat(releases): update bug and CVE modal

---

src/components/ImportForm/SecretSection/SecretSection.tsx
src/components/ImportForm/__tests__/submit-utils.spec.ts
src/components/ImportForm/submit-utils.ts
src/components/Secrets/SecretForm.tsx
src/components/Secrets/SecretModal.tsx
src/components/Secrets/SecretsForm/AddSecretForm.tsx
src/components/Secrets/SecretsForm/MultiImageCredentialForm.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/components/Secrets/SecretsForm/SourceSecretForm.tsx
src/components/Secrets/__data__/mock-secrets.ts
src/components/Secrets/__tests___/AddSecretForm.spec.tsx
src/components/Secrets/__tests___/SecretForm.spec.tsx
src/components/Secrets/__tests___/SecretModal.spec.tsx
src/components/Secrets/__tests___/SecretTypeSelector.spec.tsx
src/components/Secrets/utils/__tests__/service-account-utils.spec.ts
src/components/Secrets/utils/secret-utils.ts
src/components/Secrets/utils/service-account-utils.ts
src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.tsx
src/types/secret.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/__tests__/validation-utils.spec.ts
src/utils/create-utils.ts
src/utils/validation-utils.ts

https://issues.redhat.com/browse/HAC-5834 
PR ready for review

feat(secret): add source secrets

---

.github/workflows/pr-check.yaml

Currently, the PR check fails due to validation that the author of the PR is part of an org. 
Trying to use the same approach as Konflux QE job.
Part of https://issues.redhat.com/browse/KFLUXUI-338

test(fix): fix check for author to be part of an org

---

src/components/PipelineRun/PipelineRunListView/pipelinerun-actions.tsx

https://issues.redhat.com/browse/KONFLUX-5759
In the "Stop" and "Cancel" options in the pipeline run view, there are references to the finally tasks, added quotes to finally.
Stop Button:
<br/>
Cancel Button:

fix(KONFLUX-5759): quotes added in finally in stop and cancel buttons

---

src/routes/page-routes/release.tsx

[KFLUXUI-339](https://issues.redhat.com/browse/KFLUXUI-339)
During the release namespace migration, there is one regression. The release page of application details page is incorrect. The patch fixes the regression. 
1. visit the detail page of one application
2. visit the release tab of it
3. visit the integration tab of it
Releases of application can be shown well and we can move to integration tests easily by click the 'Integration tests' tab on the details page after we click the 'Releases'.

fix(KFLUXUI-339): releases of application details page can be shown well

---

src/routes/index.tsx
src/routes/page-routes/application.tsx

missed adding user routes to index.tsx in #149, which caused 404 errors for all User access pages 
no visual change
Test User access page: list, create, edit

fix: add user access routes to all routes

---

src/components/Releases/ReleasesListHeader.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/__tests__/ReleasesListRow.spec.tsx
src/components/Releases/__tests__/ReleasesListView.spec.tsx

No issue associated with this that I'm aware of.
This change adds release duration to the list view of releases.
As a user, I want to quickly see how long my most recent releases are taking in the list so I can compare them with each other. If they're taking longer and longer, I have a problem I need to deal with.
We happen to have a lot of real estate in the release list right now.
None.

feat: display release duration in the release list

---

src/components/ComponentRelation/cr-modals.tsx
src/components/ImportForm/ImportForm.tsx
src/components/ReleaseService/ReleaseServiceEmptyState.tsx
src/components/Releases/ReleasesEmptyState.tsx
src/components/Secrets/SecretsForm/AddSecretForm.tsx
src/components/Secrets/SecretsListPage.tsx
src/components/WhatsNext/useWhatsNextItems.ts

In https://github.com/konflux-ci/docs/pull/258 we flattened directory structures which resulted in breaking the links in the Konflux UI. This PR is updating those to be accurate again.

Fix documentation links

---

src/components/UserAccess/UserAccessForm/UserAccessForm.tsx
src/components/UserAccess/UserAccessForm/UsernameSection.tsx
src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx

[KFLUXUI-377](https://issues.redhat.com/browse/KFLUXUI-377)
Previously, when users grant user access, they input the username and the username would become inputted username chip automatically. During the SpaceBindingRequest migration, we did one improvement to ensure users need to enter 'username'.  It changes the old behavior then users would feel bad for entering.
With the current patch, users do not have to enter usernames,  losing focus and tabbing out also work. 
We tried to select roles and then input usernames and vise verse. 
and more, entering, tabbing and losing focus all works well.
https://github.com/user-attachments/assets/5fe2e062-2215-49d5-8778-8431ab7c5e23
Grant users with different ways('losing focus', 'tabbing out', 'entering') of inputting username

feat(KFLUXUI-377): enter, tab and losing focus would input username

---

.tekton/konflux-ui-pull-request.yaml
.tekton/konflux-ui-push.yaml

Task "coverity-availability-check-oci-ta" is used by pipeline task "coverity-availability-check" is or will be the
coverity-availability-check-oci-ta task is deprecated. Please use coverity-availability-check instead.

chore: replace coverity check

---

src/components/UserAccess/UserAccessForm/EditAccessPage.tsx
src/components/UserAccess/UserAccessForm/__tests__/form-utils.spec.ts
src/components/UserAccess/UserAccessForm/form-utils.ts
src/components/UserAccess/__tests__/user-access-actions.spec.ts
src/components/UserAccess/user-access-actions.ts
src/k8s/query/fetch.ts

This PR uses the naming convention for role binding names
no visual changes
Test User access:
- creation flow
- edit flow
- list view
- revoke flow

fix: use `konflux-<role>-<username>-user-actions` naming convertion for role binding names

---

src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx

https://issues.redhat.com/browse/KONFLUX-5800
We no longer have default pipeline, as a fix we removed the button.

fix(KONFLUX-5800): rollback to default pipeline button removed

---

src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/ReleasesListHeader.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/__data__/mock-release-data.ts
src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/types/release.ts
src/utils/release-utils.ts

No issues on file that I'm aware of.
There are two things changing here:
* First, I added a link to the managed pipeline runs associated with each Release the release list. The most common thing I do in the UI is navigate to the list of releases, click on a release only to find the managed pipelinerun link and click it. I never actually stop on the release details page; maybe 1 in 100 times. By presenting this link on the release list, it will save users a click when they're diving in to troubleshoot something.
* Second, the release service gained a new API some time ago for "tenant release pipelines" but we've just never shown them in the UI. The change here adds a link to the tenant release pipeline in the list (just like I added the managed ones) and it also adds the tenant release …

Pipelinerun links in release list

---

e2e-tests/BaseContainerfile
e2e-tests/Containerfile
e2e-tests/tests/basic-happy-path.spec.ts
pr_check.sh

https://issues.redhat.com/browse/KFLUXUI-338
Quit podman if the test lasts longer than 1 hour.
Update Chrome and Cypress version to lower occurrence of `Socket connection lost` issue.
Switch to default `dockert-build-oci-ta` pipeline.
Fix test for Cancelled pipeline (issue happened due to PaC update in Konflux backend).

test: add podman timeout for 1 hour

---

src/components/ApplicationDetails/__data__/WorkflowTestUtils.ts
src/components/ComponentRelation/__tests__/useComponentRelationAction.spec.ts
src/components/ComponentRelation/useComponentRelationAction.ts

[KONFLUX-5796](https://issues.redhat.com/browse/KONFLUX-5796)
Without the patch, when the app has a single component, the nudge action is disabled.
With the patch, when the app has a single component and there are one more components in the namespace, the nudging action would be enabled.
Note:
When there is no component, or there is one single component in the namespace, the nudging action would be kept as disabled.
1. create one app with one component and try to update the component relationship
Result:
When there is no other components in the namespace, we cannot update the relationship
When there is one more components in the namespace, we can update the relationship
2. create one app without component
Result:
we cannot update the relationship

fix(KONFLUX-5796): the nudging should be enabled for app has a single component

---

src/components/Commits/CommitsListPage/CommitsListRow.tsx

<a href="https://issues.redhat.com/browse/KONFLUX-5814">KONFLUX-5814</a>
Strings present in "By user" column in latest commit tab of Activity was overflowing to other column, fixed using truncate.

fix(KONFLUX-5814): fixed strings overflow to other tab

---

src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueModal.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueSection.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/AddIssueSection.spec.tsx

https://issues.redhat.com/browse/KFLUXUI-371
CVE Modal is disabled because of validation errors. This PR fixes validation issues

fix(release): update cve modal

---

src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
src/components/SnapshotDetails/SnapshotDetailsView.tsx
src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx
src/components/SnapshotDetails/tabs/SnapshotOverview.tsx

This fixes: https://issues.redhat.com/browse/KFLUXUI-375
In this PR, we're fixing an issue on the "Snapshots Details Page" where a given snapshot might not have any `labels` inside its `metadata`.
By using optional chaining (`snapshot?.metadata?.labels`), we prevent errors when trying to access label keys.
**Before the changes in this PR (error/bug):**
**After the changes in this PR (fix):**
1. Basically you need to have a snapshot with no "labels". Buut, since I was not able to reproduce such scenario, I used a tool called `HTTP Toolkit` and I edited the response from the endpoint to **not** return any `labels` inside the `metadata` object 🙂 
2. Alternatively, you can follow a much smarter approach (suggested by Cara 🙂) to edit the snapshot.yaml via `oc`/`kubectl` removing the `labels`. …

KFLUXUI-375 - [Snapshots Details Page] Fix: handle nullable 'labels' field

---

e2e-tests/tests/basic-happy-path.spec.ts
src/components/Components/ComponentDetails/tabs/ComponentDetailsTab.tsx

[KFLUXUI-226](https://issues.redhat.com/browse/KFLUXUI-226)
Watch for changes in `component` resource making the label update automatically in `ComponentDetailTab`. Adjust the the E2E test to look for the `Merge pull request` `ComponentDetailTab` and then click on it.
1. Run the E2E test
2. In the 'Explore Pipeline runs Tab' suite, check the 'Merge the auto-generated PR, and verify the event status on modal' test if it pass and check for a component named `Custom` after closing the pipeline modal (modal we send the pr to github and merge the first pipeline)
Support test:
1. Create a new component
2. Open `ComponentDetailTab` page
3. Wait for some seconds. you should see the label change from `Send pull request` to `Merge pull request`.

fix(KFLUXUI-226): check if the pipeline status change automatically on ComponentDetailsTab component

---

src/components/WhatsNext/WhatsNextSection.tsx
src/components/WhatsNext/__tests__/WhatsNextSection.spec.tsx
src/components/WhatsNext/useWhatsNextItems.ts

<a href="https://issues.redhat.com/browse/KFLUXUI-149">KFLUXUI-149</a>
Close button added on each card allowing to close the card in the what's Next Section under Application.
<br>
<hr>
When all the cards are closed, What's next option is not shown
When any card is closed , it will not be redisplayed.

chore(KFLUXUI-149): User can close "What's next" tiles

---

pr_check.sh

fixes an issue with uploading test results to Sealights
Fixes this error seen in the log:
```
+ slnodejs uploadReports --teststage konflux-ui-e2e --buildsessionidfile buildSessionId --reportfile junit-0253c5255f4a0c4df6d47b77c3693736.xml --token ***
10:10:41.025Z INFO NodeJS-Agent: Starting sealights agent with command 'startExecution',  agentId: xxx
10:10:41.087Z ERROR NodeJS-Agent: Failed to read buildsessionidfile. Error Error: ENOENT: no such file or directory, open 'buildSessionId'
```
See the log of this PR's e2e check run:
```
+ slnodejs uploadReports --teststage konflux-ui-e2e --buildsessionidfile buildSessionId --reportfile ./artifacts/junit-106a4f25bae42b65f65d915c0211da40.xml --token ***
05:11:17.844Z INFO NodeJS-Agent: Starting sealights agent with command 'startExecution', …
```

fix: uploading test results to Sealights

---

src/components/Applications/ApplicationListHeader.ts
src/components/Applications/ApplicationListView.tsx
src/components/Releases/ReleasesListHeader.tsx
src/shared/components/table/__tests__/utils.spec.tsx
src/shared/components/table/utils.ts

This fixes the issue https://issues.redhat.com/browse/KONFLUX-7750
This PR implements sorting by name on the "Applications" page. While working on this feature, I noticed a similar behavior on the "Releases" page. So as a result,  I refactored the logic for creating table headers into a more generic utility function called `createTableHeaders`, which is now used on both pages.
**Applications page:**
**Releases page (to show that nothing changes and it still works as expected):**
1. Make sure you have a few applications
2. Go to "Applications" page and now you'll notice that it's possible to sort the name column
3. ☕ 
Additional testing:
1. Since I also updated `ReleasesListHeader` to use the `createTableHeaders` utilities, you can also check the "Releases" page to see that it continues …

KONFLUX-7750: Fix sorting issue on Applications list by name

---

src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/CVEFormContent.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/ComponentField.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/StatusDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/ReleasePlanDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/SnapshotDropdown.spec.tsx
src/components/Secrets/__tests___/ApplicationDropdown.spec.tsx
src/components/Secrets/__tests___/ImagePullSecretForm.spec.tsx
src/components/Secrets/__tests___/SecretTypeSelector.spec.tsx
src/components/Secrets/__tests___/SecretTypeSubForm.spec.tsx
src/components/Secrets/__tests___/SourceSecretForm.spec.tsx
src/components/UserAccess/UserAccessForm/__tests__/RoleSection.spec.tsx
src/shared/components/dropdown/BasicDropdown.scss
src/shared/components/dropdown/BasicDropdown.tsx
src/shared/components/formik-fields/__tests__/DropdownField.spec.tsx

[KFLUXUI-330](https://issues.redhat.com/browse/KFLUXUI-330)
Components of Patterfly are interdependent. To ensure the compatible, let us replace the deprecated dropdown with the dropdown matched with the current Patternfly version.
The current dropdown removed the usage of DropdownToggle and DropdownButton and support the value for 'onSelect' function. In our BasicDropdown, we define our DropdownToggle component by ourselves.
https://github.com/user-attachments/assets/f192e9ca-a95c-4cec-8597-1607a92f884b
Visit the pages and try the dropdown to ensure they work as before.

chore(KFLUXUI-330): replace deprecated Dropdown with compatible select component

---

.eslintrc.cjs
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/release-actions.ts
src/consts/release.ts
src/utils/__tests__/release-utils.spec.ts
src/utils/release-actions.ts
src/utils/release-utils.ts

This fixes the issue https://issues.redhat.com/browse/KFLUXUI-230.
In this PR we’re introducing logic to allow a `Release` to be “re-run” or “re-triggered”.
Behind the scenes, this doesn’t actually re-run the same resource — instead, it creates a new `Release` based on the existing one.
It kinda simulates a "rerun" by cloning the original release, generating a new name with a random suffix, and updating relevant info (e.g. labels)
The implementation follows the approach described here https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/faq.md?ref_type=heads#how-do-i-retrigger-a-release, which explains how to "rerun"/"re-trigger" a release via CLI 🙂 
The screen recording below shows the "re-run" action in action 😄 …

KFLUXUI-230: Add support for "re-running" a Release

---

e2e-tests/support/pageObjects/createApplication-po.ts
e2e-tests/utils/Applications.ts
src/components/ImportForm/ComponentSection/SourceSection.tsx
src/components/ImportForm/ComponentSection/__tests__/ComponentSection.spec.tsx

[KONFLUX-7308](https://issues.redhat.com/browse/KONFLUX-7308)
When the user inputs the git repo URL, the advanced git options would open/close in a not very intuitive way. Now, the section is closed by default and can be opened only by the user clicking the open button. 
Open the form to create an application, add a component, and input a git repo URL. The advanced git section won't open, no matter the input.

fix(KONFLUX-7308): don't expand/collapse advanced git options while typing url

---

src/components/Components/LinkedSecretsListView/LinkedSecretsListHeader.tsx
src/components/Components/LinkedSecretsListView/LinkedSecretsListRow.tsx
src/components/Components/LinkedSecretsListView/LinkedSecretsListView.scss
src/components/Components/LinkedSecretsListView/LinkedSecretsListView.tsx
src/components/Components/LinkedSecretsListView/__tests__/LinkedSecretsListView.spec.tsx
src/components/Components/LinkedSecretsListView/index.ts
src/components/Components/__data__/mock-data.ts
src/components/Components/component-actions.tsx
src/hooks/__data__/mock-data.ts
src/hooks/__tests__/useLinkedSecrets.spec.ts
src/hooks/__tests__/useServiceAccount.spec.ts
src/hooks/useLinkedSecrets.ts
src/hooks/useServiceAccount.ts
src/routes/page-routes/components.tsx
src/routes/paths.ts

Fixes https://issues.redhat.com/browse/KFLUXUI-424
Please, review https://github.com/konflux-ci/konflux-ui/pull/217 first :)
This PR adds the "Manage Linked Secrets" page, which displays all secrets linked to a given component.
1. "Manage Linked Secrets" page:
https://github.com/user-attachments/assets/a34d5230-f979-4f3f-b37b-2e98c3636e8f
2.  Adding a new secret ("Secrets" page) and then checking the new secret in the "Manage Linked Secrets" page:
https://github.com/user-attachments/assets/61dcda05-10ab-4ff6-bd90-e1256e13cef7
1. Link a secret to a given component
2. Go to Components List page
3. Find your component, click on the "three dots" and select the "Manage linked secrets" action
4. You should navigate to the "Manage linked secrets" page
5. ☕

KFLUXUI-424: Add "Manage Linked Secrets" page

---

src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx

Fixes https://issues.redhat.com/browse/KONFLUX-6148
The `cosign download sbom` command was failing because the component did not yet have the `status.lastPromotedImage` set. Previously, we used the `getLastestImage()` utility, which falls back to `spec.containerImage` when `status.lastPromotedImage` is unavailable.
However, `spec.containerImage` does not include an image tag, and without a tag, the `cosign download sbom` command fails.
This PR fixes the issue by explicitly using `status.lastPromotedImage` in the `ComponentLatestBuild` component, avoiding the fallback and ensuring the command is executed with a properly tagged image.
1. Example of broken SBOM command (due to missing image tag in containerImage):
```
cosign download sbom …
```

KONFLUX-6148: Fix 'cosign download sbom' command failing due to missing image tag

---

src/components/Components/LinkedSecretsListView/LinkedSecretsListRow.tsx
src/components/Components/LinkedSecretsListView/LinkedSecretsListView.tsx
src/components/Components/LinkedSecretsListView/LinkedSecretsToolbar.tsx
src/components/Components/LinkedSecretsListView/__tests__/LinkedSecretsListView.spec.tsx

Fixes https://issues.redhat.com/browse/KFLUXUI-419
Please, review https://github.com/konflux-ci/konflux-ui/pull/221 first :)
This PR introduces logic to filter linked secrets by name on the "Manage linked secrets" page.
https://github.com/user-attachments/assets/7edf1f92-42a2-484d-bc45-636b6f8619b2
1. Go to Components List page
2. Find a component, click on the "three dots" and select the "Manage linked secrets" action
3. You should navigate to the "Manage linked secrets" page
4. Interact with the "Filter by name" input
5. ☕

KFLUXUI-419: [Manage linked secrets] Add filtering by name

---

src/components/NamespaceList/NamespaceListView.tsx

Fixes: https://issues.redhat.com/browse/KFLUXUI-431
Fixed namespaces to be sorted alphabetically instead of date.
Before ordering alphabetically:
After ordering alphabetically:
Open the website. Navigate to Namespace page -> notice that the table is now ordered alphabetically.

fix(KFLUXUI-431): namespaces order

---

src/components/Secrets/SecretsForm/AddSecretForm.tsx
src/components/Secrets/SecretsListView/SecretsList.tsx
src/components/Secrets/SecretsListView/SecretsListHeaderWithComponents.tsx
src/components/Secrets/SecretsListView/SecretsListRowWithComponents.tsx
src/components/Secrets/__data__/mock-secrets.ts
src/components/Secrets/__tests___/SecretsListView.spec.tsx
src/components/Secrets/secret-actions.ts
src/components/Secrets/secret-modal.tsx
src/components/Secrets/utils/__tests__/service-account-utils.spec.ts
src/components/Secrets/utils/service-account-utils.ts
src/hooks/__tests__/useLinkedServiceAccounts.spec.tsx
src/hooks/useLinkedServiceAccounts.ts
src/types/secret.ts

[KFLUXUI-417](https://issues.redhat.com/browse/KFLUXUI-417)
The patch is aimed to show the components number linked to the current secret in the secret list page.
When loaded, the number would be shown. While, when loading, the spinner would be shown:
When error happens, the Error would be shown:
and also the tootips when user mouse over:
For those secrets which are not able to link service accounts, the column would be shown as '-':
Add the secrets and choose components to link then check whether the number of component shown in the secret list page is expected.

  feat(KFLUXUI-417): add the 'Components' column for secret list page

---

src/__data__/pipelinerun-data.ts
src/components/Activity/ActivityTab.tsx
src/components/Activity/__tests__/ActivityTab.spec.tsx
src/components/PipelineRun/PipelineRunListView/PipelineRunListHeader.tsx
src/components/PipelineRun/PipelineRunListView/PipelineRunListRow.tsx
src/components/PipelineRun/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx
src/shared/components/table/Table.tsx
src/utils/__tests__/pipeline-utils.spec.ts
src/utils/pipeline-utils.ts

Fixes https://issues.redhat.com/browse/KONFLUX-5940
This PR adds a new column, **"Test result"**, to the PipelineRun List View. It displays the test result parsed from either the `TEST_OUTPUT` or `HACBS_TEST_OUTPUT` status result of the PipelineRun.
To understand some of the choices made in this PR, please check the comments on the JIRA ticket — there were helpful discussions there. 🙂
Example of how these changes look like with different `TEST_OUTPUT` results:
https://github.com/user-attachments/assets/b410aa1b-ca1f-4c0b-b3e4-f832a4ebc101
1. You can go to Applications -> select one application -> Activity -> Pipeline runs tab
2. You'll be able to see a new column (`Test result`)
3. If you wanna try to test different types of results as `TEST_OUTPUT`, I have a simple task example:
```yaml …
```

KONFLUX-5940 - Add "Test result" column to PipelineRun List View

---

src/components/Commits/CommitDetails/tabs/CommitsPipelineRunTab.tsx
src/hooks/__tests__/usePipelineRuns.spec.ts
src/hooks/usePipelineRuns.ts
src/utils/commits-utils.ts

This fixes the issue https://issues.redhat.com/browse/KFLUXUI-232
This PR is adding the changes to allow displaying in the "Commit Details - PipelineRun Tab", the `PipelineRun`s that doesn't have a component directly related to it.
Before the fix (notice that the PipelineRun `tenant-bdvhf` is not displayed):
With the fix:
1. Find some `PipelineRun` that doesn't have a component
2. Open the Commit Details - PipelineRuns Tab
3. The "component-less" `PipelineRun` should be listed there
4. ☕

KFLUXUI-232: [Commit Details - PipelineRun Tab] Update to also show "component-less" PipelineRuns

---

src/components/Commits/CommitsListPage/CommitsListView.tsx
src/components/Commits/CommitsListPage/__tests__/CommitsListView.spec.tsx
src/hooks/__tests__/useBuildPipelines.spec.ts

Fixes https://issues.redhat.com/browse/KFLUXUI-521
This PR updates the `CommitsListView` component to forward the `componentName` prop to the `useBuildPipelines` hook. When provided, this ensures only the PipelineRuns related to the specified component are shown.
1. **Before the fix:** the Commits tab shows commits unrelated to the `ea2e53` component.
https://github.com/user-attachments/assets/445fd628-2888-4eb9-a6d2-22e9c4acf3a8
2. **After the fix:** only commits associated with the `ea2e53` component are shown.
1. use an application that has multiple components; this increases the chance of having commits unrelated to a specific component.
2. navigate to the "Component Details → Activity" tab, then select the "Commits" sub-tab.
3. confirm that only commits related to the selected …

KFLUXUI-521: [CommitsListView] show component-specific commits when applicable

---

src/components/PipelineRun/PipelineRunListView/PipelineRunsListView.tsx
src/components/TabsLayout/TabsLayout.tsx

Fixes https://issues.redhat.com/browse/KFLUXUI-435
This PR addresses an issue where the list of PipelineRuns was not consistently sorted in the UI.
During investigation, I found that the `useRuns` hook does sort the `runs` array (based on `metadata.creationTimestamp`). However, the final list (`rResources`) is created by merging `runs` with Tekton Results (`trResources`) using:
```typescript
const rResources =
runs && trResources
? uniqBy([...runs, ...trResources], (r) => r.metadata.name)
: runs || trResources;
```
This merge can affect the original sorting. I thought about sorting the merged result inside `useRuns`, but since that hook is used in many places, I thought it could introduce unintended side effects.
To keep the change localized, I sorted the `pipelineRuns` array directly in …

KFLUXUI-435 - Fix: PipelineRuns not sorted in PipelineRunsListView

---

src/components/Components/LinkSecret/LinkSecret.tsx
src/components/Components/LinkSecret/SecretSelector.tsx

<a href="https://issues.redhat.com/browse/KFLUXUI-529">KFLUXUI-529</a>
Adjusted the Link Secret modal size to be similar with Unlink secret modal within same page.

style(KFLUXUI-529): Link Secret modal updated to small variant

---

src/components/Filter/generic/FilterContext.tsx
src/components/Filter/generic/__tests__/FilterContext.spec.tsx

Fixes https://issues.redhat.com/browse/KONFLUX-8605
In this PR we're improving the way the filter value is being parsed in the `FilterContextProvider`. It fixes an error when `JSON.parse()` is being used to try to parse a value that's a plain string.
Before:
https://github.com/user-attachments/assets/61275dcc-473e-4ab4-95fc-d19f7227b5de
After:
https://github.com/user-attachments/assets/ecd9b782-966e-4c71-ae90-a63a53d9bfed
1. navigate to a "PipelineRuns" tab
2. find a PipelineRun that can be "rerun"
3. try to re-run it
4. it should work just fine, no crashes
5. :coffee:

KONFLUX-8605: [Filter] safely parse filter values

---

src/components/Commits/CommitDetails/tabs/__tests__/CommitsPipelineRunTab.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/SnapshotDropdown.tsx
src/components/SnapshotDetails/SnapshotDetailsView.tsx
src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx
src/components/SnapshotDetails/tabs/SnapshotOverview.tsx
src/hooks/useSnapshots.ts

Fixes https://issues.redhat.com/browse/KFLUXUI-542
This PR is updating both `useSnapshot` and `useSnapshotsForApplication` hooks to use `useK8sAndKarchResource` / `useK8sAndKarchResources` in order to fetch snapshots from both kubernetes and kubearchive.
The places that were using those hooks were updated in order to handle the refactor correctly.
Also, tests were updated to reflect the new changes :)
Snapshot Details still works as expected:
https://github.com/user-attachments/assets/a11d7b69-514d-4a7f-bab8-c3ee13c55529
Snapshots Dropdown still works as expected:
https://github.com/user-attachments/assets/470fd5c2-01ed-442e-b1f4-ac21ac63423c
Also showing API calls:
https://github.com/user-attachments/assets/9209b35b-8d9b-446b-87fc-0aee9e296366
There are two main pages that were affected …

KFLUXUI-542 [Snapshots] migrate to useK8sAndKarchResource for k8s-karch fetching

---

AI_authorized_emails.txt
src/components/Secrets/SecretsForm/SecretLinkOption.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/components/Secrets/__tests___/SecretLinkOption.spec.tsx
src/components/Secrets/utils/secret-utils.ts
src/consts/secrets.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/KFLUXUI-548
We need provide 'Do not link' to add secret page for secret link options. There is no change in import secret page.
- Recording for the option:
[Kooha-2025-06-24-22-34-19.webm](https://github.com/user-attachments/assets/f04fe6df-3577-4492-85ff-06af3fbe46b3)
- Recording for adding & importing secrets to ensure there is no regression
[Kooha-2025-06-24-22-34-19.webm](https://github.com/user-attachments/assets/c2a76599-8fee-458f-abbd-7b35b315be5a)
Just visit the add  & import secret page.

feat(KFLUXUI-548): add do not link option for select link options

---

e2e-tests/tests/basic-happy-path.spec.ts
e2e-tests/utils/Applications.ts
src/components/UserAccess/RBListRow.tsx
src/components/UserAccess/UserAccessForm/UserAccessForm.tsx
src/components/UserAccess/UserAccessForm/UserAccessFormPage.tsx
src/components/UserAccess/UserAccessForm/__tests__/UserAccessFormPage.spec.tsx
src/components/UserAccess/UserAccessForm/form-utils.ts
src/components/UserAccess/UserAccessListView.tsx
src/components/UserAccess/__tests__/UserAccessListView.spec.tsx
src/types/role-binding.ts

[KFLUXUI-520](https://issues.redhat.com/browse/KFLUXUI-520)
As per [slack thread](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1746196905597379), a role binding without the `subjects` field is valid and should be supported. This PR makes the `subjects` field optional and handles cases when it is missing.

fix(KFLUXUI-520): make subjects in role binding optional

---

AI_authorized_emails.txt
src/components/EnterpriseContract/EnterpriseContractTable/EnterpriseContractRow.tsx
src/components/EnterpriseContract/__tests__/SecurityEnterpriseContractTab.spec.tsx

https://issues.redhat.com/browse/KONFLUX-8863
The link of the pipelinerun security tab should be pointed to exact component
Without the patch:
With the patch:
Find one integration pipelinerun and open the security tab, check the component links work well.

fix(KONFLUX-8863): fix the component link of the pipelinerun security tab

---

src/components/Secrets/SecretsListView/SecretsListView.tsx
src/components/Secrets/__tests___/SecretsListView.spec.tsx

Assisted-by: Cursor
https://issues.redhat.com/browse/KFLUXUI-549
The SecretsListView page did not handle the error returned by the useSecrets hook, leading to accessing information that was possibly undefined.

fix(KFLUXUI-549): handle errors in SecretsListView

---

src/consts/pipelinerun.ts
src/hooks/usePACStatesForComponents.ts

[KFLUXUI-473](https://issues.redhat.com/browse/KFLUXUI-473)
WIP
Fix k8s query selection for pipelineRuns of component form GitLab
Before:
After:
1. Create a component from GitLab
2. No warning message should appear at the top Component List page

fix(KFLUXUI-473): filter correctly pipelineRuns from GitLab

---

src/assets/Commit.svg

https://issues.redhat.com/browse/KFLUXUI-732
Changes 2 different svgs with same design to the same dimensions.
Before
https://github.com/user-attachments/assets/6cc7a952-8e06-405f-8d2c-482e6ccbaf22
After
https://github.com/user-attachments/assets/a104d6b4-329a-45b2-beea-e8d3f99845fe

fix: changes different svgs with same design to same dimensions
